<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quantity_field</name>
   <tag></tag>
   <elementGuidId>6b784d61-0a75-4679-800d-bb3ed94bf36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addtocart_31_EnteredQuantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addtocart_31_EnteredQuantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Qty:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a7ea43e-7038-49d2-8276-8a009a7b6db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input</value>
      <webElementGuid>0f038830-8349-4f3f-bd68-6de57e08df47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a8b449e-4e0a-42f0-bf7b-b4ada6abf5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Qty must be a number.</value>
      <webElementGuid>5ad060da-a11c-4342-9d5a-146531035021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addtocart_31_EnteredQuantity</value>
      <webElementGuid>0ebc6f9e-7689-412c-8ed7-2165cdaf7ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtocart_31.EnteredQuantity</value>
      <webElementGuid>998858ed-bb6b-4b10-9c37-04d80e04dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fc8341f-0782-4dab-b3cd-055e0b31af6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b679001a-e2f4-425b-849f-e6be48d7bb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addtocart_31_EnteredQuantity&quot;)</value>
      <webElementGuid>3e3776f1-cf0c-4b34-a7f6-f16fb3c72cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addtocart_31_EnteredQuantity']</value>
      <webElementGuid>46159cb7-b9d2-4629-bcfe-39b31962d922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/input</value>
      <webElementGuid>66a72ea7-e338-4053-9984-ebafae51b4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>35470ef7-1d7d-4349-8578-acd9d1e55236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addtocart_31_EnteredQuantity' and @name = 'addtocart_31.EnteredQuantity' and @type = 'text']</value>
      <webElementGuid>88d954d1-8082-4371-af50-2668c3b03018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
